### ISSUE TITLE
Problem consultation

### ISSUE THREAD

**Issue by XW0413** [Pter61/context_i2w#8]
I want to understand that when evaluating on the CIRR dataset, I learned from your literature that the input should be in the form of a photo of [REPLACE], [sense]. Then, when I input as shown in the figure, an error message will appear. I wonder if there is an issue with the input mode of this prompts? I hope you have time to reply to me. Thank you
<img width="1057" alt="353EE12BA8B3A0402FC47B694DAB1A91" src="https://github.com/Pter61/context-i2w/assets/118547614/16e709ff-c442-4ef6-b628-62958fba9900">

**Comment by Pter61** [comment]
Thank you for your interest in my work! The "[REPLACE]" token in the code is "<|replace|>", you can change ir in the prompt and retry. If you find it useful, feel free to star my repo~

**Comment by XW0413** [comment]
This prompt is“a photo of <|REPLACE|>, [The dog is inside a hole and not on grass]”？

**Comment by Pter61** [comment]
No, is the prompt is "a photo of <|replace|>, The dog is inside a hole and not on grass", details are in the eval_utils.py

**Comment by XW0413** [comment]
Thank you, I will study again.
